### ISSUE TITLE
Práctica Smartsheet.

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/actividad-8-planificacion-de-sprints-en-smartsheet-entrevista-metztli_team#1]
[Smartsheet.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-planificacion-de-sprints-en-smartsheet-entrevista-metztli_team/files/9947961/Smartsheet.pdf)

**Comment by Yabin-2021** [comment]
Buen trabajo
30/30

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
